version: "3.7"
services:

  ThamesThrive-staging-api:
    image: ThamesThrive/com-ThamesThrive-api:0.8.1
    environment:
      ELASTIC_HOST: http://elasticsearch:9200
      REDIS_HOST: redis://redis:6379
      LOGGING_LEVEL: info
      LICENSE: ${API_LICENSE}
      ENABLE_SEGMENTATION_WF_TRIGGERS: "yes"
      ENABLE_EVENT_DESTINATIONS: "yes"
      ENABLE_PROFILE_DESTINATIONS: "yes"
      PRODUCTION: "no"
      TRACK_DEBUG: "yes"
    ports:
      - 8686:80
    depends_on:
      - redis
      - elasticsearch

  ThamesThrive-production-api:
    image: ThamesThrive/com-ThamesThrive-api:0.8.1
    environment:
      ELASTIC_HOST: http://elasticsearch:9200
      REDIS_HOST: redis://redis:6379
      LOGGING_LEVEL: info
      LICENSE: ${API_LICENSE}
      ENABLE_SEGMENTATION_WF_TRIGGERS: "yes"
      ENABLE_EVENT_DESTINATIONS: "yes"
      ENABLE_PROFILE_DESTINATIONS: "yes"
      PRODUCTION: "yes"
    ports:
      - 8585:80
    depends_on:
      - redis
      - elasticsearch

  ThamesThrive-gui:
    image: ThamesThrive/ThamesThrive-gui:0.8.1
    ports:
      - 8787:80
    depends_on:
      - staging-api

  worker:
    image: ThamesThrive/update-worker:0.8.1
    environment:
      REDIS_HOST: redis://redis:6379

  segmentation-worker:
    image: ThamesThrive/com-ThamesThrive-segmentation-worker:0.8.1
    environment:
      ELASTIC_HOST: http://elasticsearch:9200
      REDIS_HOST: redis://redis:6379
      LOGGING_LEVEL: info
      LICENSE: ${API_LICENSE}

  scheduler-worker:
    image: ThamesThrive/com-ThamesThrive-scheduler-worker:0.8.1
    environment:
      ELASTIC_HOST: http://elasticsearch:9200
      REDIS_HOST: redis
      LOGGING_LEVEL: info
      PRODUCTION: "yes"
      LICENSE: ${API_LICENSE}
    depends_on:
      - redis
      - elasticsearch

  coping-worker:
    image: ThamesThrive/com-ThamesThrive-coping-worker:0.8.1
    environment:
      ELASTIC_HOST: http://elasticsearch:9200
      REDIS_HOST: redis://redis:6379
      LOGGING_LEVEL: info
      LICENSE: ${API_LICENSE}

  trigger-worker:
    image: ThamesThrive/com-ThamesThrive-trigger-worker:0.8.1
    environment:
      ELASTIC_HOST: http://elasticsearch:9200
      REDIS_HOST: redis://redis:6379
      LOGGING_LEVEL: info
      LICENSE: ${API_LICENSE}

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    environment:
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      discovery.type: single-node
      xpack.security.enabled: "false"
      cluster.name: contextElasticSearch
    volumes:
      - type: volume
        source: esdata
        target: /usr/share/elasticsearch/data

  redis:
    image: redis

volumes:
  esdata:
