version: "3.7"
services:

  ThamesThrive-api:
    image: ThamesThrive/ThamesThrive-api:0.8.1
    environment:
      ELASTIC_HOST: http://elasticsearch:9200
      REDIS_HOST: redis://redis:6379
      LOGGING_LEVEL: info
      DEMO: yes
      PRODUCTION: no
    ports:
      - 8686:80
    depends_on:
      - redis
      - elasticsearch

  ThamesThrive-gui:
    image: ThamesThrive/ThamesThrive-gui:0.8.1
    ports:
      - 8787:80
    depends_on:
      - ThamesThrive-api

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    environment:
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      discovery.type: single-node
      xpack.security.enabled: "false"
      cluster.name: contextElasticSearch
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  redis:
    image: redis

  worker:
    image: ThamesThrive/update-worker:0.8.1
    environment:
      REDIS_HOST: redis://redis:6379

volumes:
  elasticsearch-data:
    driver: local
